name: 🚪 Close v2 Issues

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  experimental:
    name: 🚪 Close v2 Issues
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: 📥 Install deps
        run: pnpm install --frozen-lockfile

      - name: 🚪 Close Issues
        run: |
          node -e "console.log('GH_TOKEN defined?', process.env.GH_TOKEN != null)"
          node ./scripts/close-v2-issues.mjs
